[project]
name = "ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Darshan Tarware", email = "tarwaredarshan2@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "duckduckgo-search>=8.1.1",
    "fpdf2>=2.8.8",
    "google-api-python-client>=2.198.0",
    "google-auth-httplib2>=0.4.1",
    "google-auth-oauthlib>=1.4.0",
    "google-genai>=2.18.1",
    "imageio-ffmpeg>=0.6.0",
    "openai>=3.2.0",
    "python-dotenv>=1.2.3",
    "python-telegram-bot>=22.8",
    "streamlit>=1.61.1",
    "youtube-transcript-api>=1.2.4",
    "yt-dlp>=2026.7.4",
]

[project.scripts]
ai-agent = "ai_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
